services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: raya_db
      POSTGRES_USER: raya_user
      POSTGRES_PASSWORD: raya_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U raya_user -d raya_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://raya_user:raya_password@db:5432/raya_db
      - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data: 